version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: birdie-fronend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend

  backend:
    build: ./backend
    environment:
      - PORT=3001
      - BIRDNEST_API_URL=https://assignments.reaktor.com/birdnest
    container_name: birdie-backend
