version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - BIRDNEST_API_URL=https://assignments.reaktor.com/birdnest
    container_name: birdie-backend
